### ISSUE TITLE
(unknown): Generic scrypt code is broken - please report bug!

### ISSUE THREAD

**Issue by TheRammer** [jkalbhenn/scrypt#2]
$ ./exe/test
(unknown): Generic scrypt code is broken - please report bug!
./exe/test: line 2: 318717 Aborted                 (core dumped) temp/test
$ 
$ gdb scrypt-kdf
(gdb) run testpassword
Starting program: /usr/bin/scrypt-kdf testpassword
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
(unknown): Generic scrypt code is broken - please report bug!

Program received signal SIGABRT, Aborted.
0x00007ffff7d734dc in ?? () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff7d734dc in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7d23998 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7d0d53d in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7fbb202 in crypto_scrypt () from /usr/lib/libscrypt.so
#4  0x00007ffff7fbb5d9 in scryptenc_cpuperf () from /usr/lib/libscrypt.so
#5  0x00007ffff7fbb8d2 in scrypt_set_defaults () from /usr/lib/libscrypt.so
#6  0x00007ffff7fbbd58 in scrypt_to_string_base91 () from /usr/lib/libscrypt.so
#7  0x0000555555555567 in main ()
(gdb)

**Comment by PaulRivier** [comment]
Confirmed.
